# Generated by Django 3.2 on 2021-07-18 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customers',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.RenameField(
            model_name='customers',
            old_name='Massage',
            new_name='Message',
        ),
    ]
