# Generated by Django 3.2 on 2021-07-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210718_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos')),
            ],
        ),
    ]
