# Generated by Django 3.2 on 2021-07-23 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_demovideo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DemoVideo',
        ),
    ]
